# Generated by Django 5.0.7 on 2024-07-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_iamge',
            new_name='featured_image',
        ),
    ]
