# Generated by Django 5.0.7 on 2024-07-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_featured_iamge_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.TextField(choices=[('Darft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
